apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend-learning
resources:
  - ../../base
images:
  - name: backend-learning-api
    newName: backend-learning-api
    newTag: dev
