apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend-learning
resources:
  - ../../base/configmap.yaml
  - ../../base/secret.example.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/ingress.yaml
  - ../../base/migration-job.yaml
  - ../../base/hpa.yaml
images:
  - name: backend-learning-api
    newName: backend-learning-api
    newTag: dev
