apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.example.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - migration-job.yaml
  - hpa.yaml
