[project]
name = "backend-learning-fastapi"
version = "1.0.0"
requires-python = ">=3.13,<3.14"
dependencies = [
  "alembic==1.16.5",
  "argon2-cffi==25.1.0",
  "celery==5.5.3",
  "fastapi==0.116.1",
  "httpx==0.28.1",
  "minio==7.2.16",
  "pydantic-settings==2.10.1",
  "pyjwt==2.10.1",
  "redis==6.4.0",
  "sqlalchemy[asyncio]==2.0.43",
  "uvicorn==0.35.0",
  "asyncmy==0.2.10"
]

[dependency-groups]
dev = ["mypy==1.17.1", "pytest==8.4.2", "pytest-asyncio==1.1.0", "ruff==0.12.11"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
pythonpath = ["."]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["B008"]

[tool.mypy]
python_version = "3.13"
strict = true
packages = ["app"]
